FROM python:3.13
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app

RUN chmod +x /app/worker-entrypoint.sh


ENTRYPOINT ["/app/worker-entrypoint.sh"]